from flask import Flask, request
import os

app = Flask(__name__)


@app.route("/")
def hello():
    return "Hello World!"


@app.route("/system")
def system():
    return os.system("ls")


@app.route("/system2")
def system2():
    return os.system(request.args["command"])


@app.route("/system3")
def system3():
    os.system(request.args["1"])
    os.system(request.args["2"])
    os.system(request.args["3"])
    os.system(request.args["4"])
    os.system(request.args["5"])
    os.system(request.args["6"])
    os.system(request.args["7"])
    os.system(request.args["8"])
    os.system(request.args["9"])
    os.system(request.args["10"])
    os.system(request.args["11"])
    os.system(request.args["12"])
    os.system(request.args["13"])
    os.system(request.args["14"])
    os.system(request.args["15"])
    os.system(request.args["16"])
    os.system(request.args["17"])
    os.system(request.args["18"])
    os.system(request.args["19"])
    os.system(request.args["20"])
    os.system(request.args["21"])
    os.system(request.args["22"])
    os.system(request.args["23"])
    os.system(request.args["24"])
    os.system(request.args["25"])
    os.system(request.args["26"])
    os.system(request.args["27"])
    os.system(request.args["28"])
    os.system(request.args["29"])
    os.system(request.args["30"])
    os.system(request.args["31"])
    os.system(request.args["32"])
    os.system(request.args["33"])
    os.system(request.args["34"])
    os.system(request.args["35"])
    os.system(request.args["36"])
    os.system(request.args["37"])
    os.system(request.args["38"])
    os.system(request.args["39"])
    os.system(request.args["40"])
    os.system(request.args["41"])
    os.system(request.args["42"])
    os.system(request.args["43"])
    os.system(request.args["44"])
    os.system(request.args["45"])
    os.system(request.args["46"])
    os.system(request.args["47"])
    os.system(request.args["48"])
    os.system(request.args["49"])
    os.system(request.args["50"])
    os.system(request.args["51"])
    os.system(request.args["52"])
    os.system(request.args["53"])
    os.system(request.args["54"])
    os.system(request.args["55"])
    os.system(request.args["56"])
    os.system(request.args["57"])
    os.system(request.args["58"])
    os.system(request.args["59"])
    os.system(request.args["60"])
    os.system(request.args["61"])
    os.system(request.args["62"])
    os.system(request.args["63"])
    os.system(request.args["64"])
    os.system(request.args["65"])
    os.system(request.args["66"])
    os.system(request.args["67"])
    os.system(request.args["68"])
    os.system(request.args["69"])
    os.system(request.args["70"])
    os.system(request.args["71"])
    os.system(request.args["72"])
    os.system(request.args["73"])
    os.system(request.args["74"])
    os.system(request.args["75"])
    os.system(request.args["76"])
    os.system(request.args["77"])
    os.system(request.args["78"])
    os.system(request.args["79"])
    os.system(request.args["80"])
    os.system(request.args["81"])
    os.system(request.args["82"])
    os.system(request.args["83"])
    os.system(request.args["84"])
    os.system(request.args["85"])
    os.system(request.args["86"])
    os.system(request.args["87"])
    os.system(request.args["88"])
    os.system(request.args["89"])
    os.system(request.args["90"])
    os.system(request.args["91"])
    os.system(request.args["92"])
    os.system(request.args["93"])
    os.system(request.args["94"])
    os.system(request.args["95"])
    os.system(request.args["96"])
    os.system(request.args["97"])
    os.system(request.args["98"])
    os.system(request.args["99"])
    os.system(request.args["100"])
